---
- hosts: all
  vars_prompt:
    - name: "mongodb_password"
      prompt: "Mongodb Password"
  remote_user: ubuntu
  become: yes
  tasks:
    - apt:
        update_cache: yes
        name: "{{ item }}"
      loop:
        - wget
        - git
        - docker-compose

    - name: Docker ppa key
      apt_key: 
        url: https://download.docker.com/linux/{{ansible_distribution | lower}}/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution | lower}} {{ansible_distribution_release}} stable

    - name: Install Docker
      apt:
        name: docker-ce

    - name: Posix users which can use docker
      user:
        name: "{{ ansible_user }}"
        groups:
          - docker

    - name: Allow http port
      ufw:
        rule: allow
        port: "8080"

    - name: Add Caddy APT repository
      apt_repository:
        repo: deb [trusted=yes] https://apt.fury.io/caddy/ /

    - name: Install Caddy
      apt:
        name: caddy

    - name: Create reverse proxy
      command: caddy reverse-proxy --to 127.0.0.1:8080
      ignore_errors: yes

    - name: Get docker-compose file
      get_url:
        url: https://raw.githubusercontent.com/nlesc-nano/ceiba/master/provisioning/docker-compose.yml
        dest: /tmp/docker-compose.yml

    - name: Start the app
      script: ./start_app.sh
      environment:
        MONGO_PASSWORD: '{{ mongodb_password }}'
        DOCKER_COMPOSE_FILE: /tmp/docker-compose.yml