name: build

on: [push, pull_request]

jobs:

  build:
    name: Build for (${{ matrix.python-version }}) on ubuntu-latest
    runs-on: 'ubuntu-latest' 
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8']

    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}    

      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install library
        run: |
          pip install -e .[test]

      - name: Test
        run: |
          pytest

      - name: coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          name: codecov-umbrella

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: felipez/insilico:prototype
